# 最初の10行は Line を作成しない。11行目以降はLineを作成する
# SubDef03 <- ( OddLine EvenLine? )*
SubDef03 <- OddLine*

OddLine <-  First Content >>LineTerminator?
OddLine <-- Second Content >>LineTerminator?

# EvenLine <- First Content >>LineTerminator

First  <- &r"."
Second <- &r"."

Content <-  First Any
Content <-- Second AnyWord OddLine?

Any <- r"[a-zA-Z0-9_ ]+"
AnyWord <- r"[a-zA-Z0-9_]*" >>Spacing?

Spacing <- " "+
LineTerminator <- r"\r\n|\r|\n"


